// try catch 
try{
    myfunction();
}catch(error){
    console.log(error.message)
}

   

